version: '3.8'

services:
  db:
    image: mongo
    container_name: db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jaype
      - MONGO_INITDB_ROOT_PASSWORD=joaopaulo
    ports:
      - "27017:27017"
    volumes:
      - Users/jaype/Documents/Digital Innovation One/Docker-Compose
      - /data/db
